name: Go Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'  # Remplace par ta version de Go

      - name: Install dependencies
        working-directory: go
        run: go mod tidy
        
      - name: Clone private input repo
        run: |
          git clone https://x-access-token:${{ secrets.AOC_INPUTS }}@github.com/Discobluff/advent-of-code-inputs.git inputs

      - name: Run tests
        working-directory: go
        run: go test ./...

